/**
 * CHURRASCO! — real audio layer (foley + golden-hour 3400K) with WebAudio synthesis fallback.
 *
 * Before (placeholder): every cue was synthesized from noise+biquad+osc so the
 * prototype needed no files. Now REAL WAV assets exist in `Assets/Audio/` and
 * `prototype/public/audio/` (generated by `tools/generate-audio-assets.mjs`), but
 * the synthetic engine is KEPT as fallback so the game never goes silent if a
 * file fails to load or decode. Swapping a studio recording is one file replace.
 *
 * Spec: docs/10-AUDIO.md §3 (asset list), §4 music, §5 buses, §2 sizzle bed.
 */

export type SfxId =
  | 'flip' | 'place' | 'serve' | 'perfect' | 'good' | 'burned'
  | 'coin' | 'orderIn' | 'combo' | 'levelUp' | 'charcoalLow'
  | 'uiTap' | 'uiBack' | 'uiError' | 'vipArrive';

type CtxLike = AudioContext & {
  // keep type flexible for Node harness stub
  createGain(): GainNode;
  createOscillator(): OscillatorNode;
  createBufferSource(): AudioBufferSourceNode;
  createBiquadFilter(): BiquadFilterNode;
  createBuffer(channels: number, length: number, sampleRate: number): AudioBuffer;
  decodeAudioData(ab: ArrayBuffer): Promise<AudioBuffer>;
};

interface Manifest {
  sfx: any;
  music: any;
}

/** Map cue -> file(s). Mirrors manifest.json but hardcoded for resilience (manifest is best-effort). */
const FILE_MAP: Record<SfxId, string | string[]> = {
  flip: ['sfx_flip_01.wav','sfx_flip_02.wav','sfx_flip_03.wav','sfx_flip_04.wav'],
  place: ['sfx_place_01.wav','sfx_place_02.wav'],
  serve: 'sfx_serve.wav',
  perfect: ['sfx_perfect_01.wav','sfx_perfect_02.wav','sfx_perfect_03.wav'],
  good: 'sfx_good.wav',
  burned: 'sfx_burned.wav',
  coin: ['sfx_coin_01.wav','sfx_coin_02.wav','sfx_coin_03.wav'],
  orderIn: 'sfx_order_in.wav',
  combo: 'sfx_combo_05.wav', // dynamic tier maps in play()
  levelUp: 'sfx_level_up.wav',
  charcoalLow: 'sfx_charcoal_low.wav',
  uiTap: 'sfx_ui_tap.wav',
  uiBack: 'sfx_ui_back.wav',
  uiError: 'sfx_ui_error.wav',
  vipArrive: 'sfx_vip_arrive.wav',
};

const MUSIC_FILES: Record<string,string> = {
  home: 'mus_home.wav',
  gameplay: 'mus_gameplay.wav',
  result: 'mus_result.wav',
};

export class PrototypeAudio {
  private ctx: CtxLike | null = null;
  private master: GainNode | null = null;
  private musicGain: GainNode | null = null;
  private sfxGain: GainNode | null = null;
  private noise: AudioBuffer | null = null;
  private buffers = new Map<string, AudioBuffer>();
  private manifest: Manifest | null = null;
  private loading: Promise<void> | null = null;
  private lastVariant = new Map<string, number>();
  private coinRun = 0;
  private coinRunAt = 0;
  private currentMusic: { src: AudioBufferSourceNode; gain: GainNode } | null = null;
  muted = false;
  /** True once at least one real buffer decoded — used for UI badge */
  hasRealAssets = false;

  unlock(): void {
    if (this.ctx) {
      if (this.ctx.state === 'suspended') void this.ctx.resume();
      // kick load if not started
      if (!this.loading) this.loading = this.loadAssets();
      return;
    }
    const Ctor = (globalThis as any).AudioContext;
    if (!Ctor) return;
    try {
      const ctx = new Ctor() as CtxLike;
      this.ctx = ctx;
      this.master = ctx.createGain();
      this.master.gain.value = this.muted ? 0 : 0.85;
      this.musicGain = ctx.createGain(); this.musicGain.gain.value = 0.6; this.musicGain.connect(this.master);
      this.sfxGain = ctx.createGain(); this.sfxGain.gain.value = 1.0; this.sfxGain.connect(this.master);
      this.master.connect(ctx.destination);
      this.noise = this.makeNoise(ctx);
      if (ctx.state === 'suspended') void ctx.resume();
      this.loading = this.loadAssets();
    } catch {
      this.ctx = null;
    }
  }

  setMuted(m: boolean): void {
    this.muted = m;
    if (this.master) this.master.gain.value = m ? 0 : 0.85;
  }

  /** Volume 0..1 (master already 0.85) */
  setMusicVolume(v: number): void { if(this.musicGain) this.musicGain.gain.value = Math.max(0, Math.min(1, v))*0.6; }
  setSfxVolume(v: number): void { if(this.sfxGain) this.sfxGain.gain.value = Math.max(0, Math.min(1, v)); }

  private makeNoise(ctx: CtxLike): AudioBuffer {
    const len = Math.floor(ctx.sampleRate * 2);
    const buf = ctx.createBuffer(1, len, ctx.sampleRate);
    const data = buf.getChannelData(0);
    for (let i = 0; i < len; i++) data[i] = Math.random() * 2 - 1;
    return buf;
  }

  private variant(cue: string, count: number): number {
    let v = Math.floor(Math.random() * count);
    if (count > 1 && v === this.lastVariant.get(cue)) v = (v + 1) % count;
    this.lastVariant.set(cue, v);
    return v;
  }

  private get now(): number { return this.ctx ? this.ctx.currentTime : 0; }

  /** Try to fetch + decode real assets; silent fallback to synth if anything fails (offline, Node harness, 404) */
  private async loadAssets(): Promise<void> {
    if (!this.ctx) return;
    const candidates = ['/public/audio/manifest.json', '/audio/manifest.json', '/prototype/public/audio/manifest.json', 'prototype/public/audio/manifest.json'];
    let manifestUrl: string | null = null;
    let manifestTxt: string | null = null;
    for (const u of candidates) {
      try {
        const r = await fetch(u);
        if (r.ok) { manifestTxt = await r.text(); manifestUrl = u; break; }
      } catch {}
    }
    if (!manifestTxt) {
      // try direct without manifest: probe one file
      manifestUrl = null;
    } else {
      try { this.manifest = JSON.parse(manifestTxt); } catch {}
    }
    const base = manifestUrl ? manifestUrl.slice(0, manifestUrl.lastIndexOf('/')) : null;
    const bases = base ? [base] : ['/public/audio','/audio','prototype/public/audio','/prototype/public/audio'];
    // collect file list
    const files = new Set<string>();
    for (const v of Object.values(FILE_MAP)) {
      if (Array.isArray(v)) v.forEach(f=>files.add(f)); else files.add(v as string);
    }
    // combo variants
    ['sfx_combo_05.wav','sfx_combo_10.wav','sfx_combo_15.wav','sfx_combo_20.wav'].forEach(f=>files.add(f));
    Object.values(MUSIC_FILES).forEach(f=>files.add(f));
    // also grill loops
    files.add('sfx_grill_sizzle_loop.wav'); files.add('sfx_charcoal_crackle_loop.wav');

    for (const file of files) {
      let decoded: AudioBuffer | null = null;
      for (const b of bases) {
        const url = `${b}/${file}`;
        try {
          const r = await fetch(url);
          if (!r.ok) continue;
          const ab = await r.arrayBuffer();
          decoded = await (this.ctx as any).decodeAudioData(ab.slice(0));
          break;
        } catch {}
      }
      if (decoded) {
        this.buffers.set(file, decoded);
        this.hasRealAssets = true;
      }
    }
    // sizzle bed is special: keep noise buffer even if real loop exists
  }

  private playBuffer(file: string, gain=0.9, rate=1, bus: 'sfx'|'music' = 'sfx'): boolean {
    const ctx = this.ctx;
    const buf = this.buffers.get(file);
    if (!ctx || !buf) return false;
    try {
      const src = ctx.createBufferSource();
      src.buffer = buf;
      src.playbackRate.value = rate;
      const g = ctx.createGain();
      g.gain.value = gain;
      src.connect(g);
      g.connect(bus==='music' ? this.musicGain! : this.sfxGain!);
      src.start(this.now);
      return true;
    } catch { return false; }
  }

  private noiseBurst(t0: number, dur: number, gain: number, filter: BiquadFilterType, freq: number, q=1, sweepTo?: number): void {
    const ctx = this.ctx!;
    const src = ctx.createBufferSource();
    src.buffer = this.noise;
    src.loop = true;
    src.playbackRate.value = 0.9 + Math.random()*0.25;
    const bq = ctx.createBiquadFilter();
    bq.type = filter; bq.frequency.setValueAtTime(freq, t0); bq.Q.value=q;
    if (sweepTo!==undefined) bq.frequency.exponentialRampToValueAtTime(Math.max(40,sweepTo), t0+dur);
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002,gain), t0+dur*0.15);
    g.gain.exponentialRampToValueAtTime(0.0001, t0+dur);
    src.connect(bq); bq.connect(g); g.connect(this.sfxGain!);
    src.start(t0, Math.random()*1.5);
    src.stop(t0+dur+0.02);
  }

  private tone(t0: number, dur: number, freq: number, gain: number, type: OscillatorType='sine', glideTo?: number, attack=0.008): void {
    const ctx = this.ctx!;
    const osc = ctx.createOscillator();
    osc.type=type; osc.frequency.setValueAtTime(freq,t0);
    if(glideTo!==undefined) osc.frequency.exponentialRampToValueAtTime(Math.max(20,glideTo), t0+dur);
    const g=ctx.createGain();
    g.gain.setValueAtTime(0.0001,t0);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002,gain), t0+attack);
    g.gain.exponentialRampToValueAtTime(0.0001, t0+dur);
    osc.connect(g); g.connect(this.sfxGain!);
    osc.start(t0); osc.stop(t0+dur+0.02);
  }

  /** Public play — prefers real asset, falls back to synth */
  play(id: SfxId, opts: { combo?: number; intensity?: number } = {}): void {
    if (this.muted || !this.ctx || !this.sfxGain) return;
    const t=this.now;
    const combo=opts.combo??0;

    // Try real asset first
    const tryReal = (file:string, gain=0.9, rate=1):boolean=> this.playBuffer(file,gain,rate,'sfx');

    switch(id){
      case 'flip': {
        const files=FILE_MAP.flip as string[];
        const v=this.variant('flip', files.length);
        if(tryReal(files[v], 0.9, 0.95+Math.random()*0.12)) return;
        const base=1500+v*220;
        this.noiseBurst(t,0.3,0.16+v*0.01,'highpass',base,0.8,base*0.45);
        for(let i=0;i<3+v;i++) this.noiseBurst(t+0.02+i*0.035,0.05,0.05,'bandpass',2400+Math.random()*1800,6);
        break;
      }
      case 'place': {
        const files=FILE_MAP.place as string[];
        const v=this.variant('place', files.length);
        if(tryReal(files[v],0.85)) return;
        this.noiseBurst(t,0.16,0.13,'bandpass',900+v*260,1.4,420);
        this.tone(t,0.12,150-v*18,0.1,'sine',80);
        break;
      }
      case 'serve':
        if(tryReal(FILE_MAP.serve as string,0.9)) return;
        this.tone(t,0.1,620,0.09,'triangle',880);
        this.noiseBurst(t+0.02,0.14,0.06,'highpass',3200,0.7);
        break;
      case 'perfect': {
        const files=FILE_MAP.perfect as string[];
        const v=this.variant('perfect', files.length);
        if(tryReal(files[v],0.9)) return;
        const root=660*Math.pow(2,v/12);
        this.tone(t,0.34,root,0.13,'triangle');
        this.tone(t+0.05,0.3,root*1.5,0.09,'sine');
        this.tone(t+0.1,0.34,root*2,0.07,'sine');
        break;
      }
      case 'good':
        if(tryReal(FILE_MAP.good as string,0.85)) return;
        this.tone(t,0.16,520,0.09,'sine',640);
        break;
      case 'burned':
        if(tryReal(FILE_MAP.burned as string,0.9)) return;
        this.noiseBurst(t,0.45,0.14,'highpass',2600,0.6,700);
        this.tone(t+0.03,0.28,120,0.14,'sine',60);
        break;
      case 'coin': {
        const runT=this.ctx.currentTime;
        if(runT - this.coinRunAt > 1.2) this.coinRun=0;
        this.coinRunAt=runT;
        const step=Math.min(this.coinRun++,7);
        const files=FILE_MAP.coin as string[];
        const v=this.variant('coin', files.length);
        const rate=Math.pow(2, step/12);
        if(tryReal(files[v],0.85, rate)) return;
        const f=(900+v*90)*Math.pow(2, step/12);
        this.tone(t,0.09,f,0.085,'triangle',f*1.35);
        this.tone(t+0.02,0.07,f*1.5,0.05,'sine');
        break;
      }
      case 'orderIn':
        if(tryReal(FILE_MAP.orderIn as string,0.85)) return;
        this.tone(t,0.5,880,0.1,'sine'); this.tone(t,0.32,1320,0.05,'sine');
        break;
      case 'combo': {
        const tier=combo>=20?4:combo>=15?3:combo>=10?2:combo>=5?1:0;
        const map:Record<number,string>={0:'sfx_combo_05.wav',1:'sfx_combo_05.wav',2:'sfx_combo_10.wav',3:'sfx_combo_15.wav',4:'sfx_combo_20.wav'};
        if(tryReal(map[tier]||'sfx_combo_05.wav',0.9)) return;
        const root=440*Math.pow(2,tier*2/12);
        for(let i=0;i<3;i++) this.tone(t+i*0.07,0.22,root*Math.pow(2,i*4/12),0.1-i*0.02,'triangle');
        break;
      }
      case 'levelUp':
        if(tryReal(FILE_MAP.levelUp as string,0.9)) return;
        [523,659,784,1046].forEach((f,i)=>this.tone(t+i*0.1,0.4,f,0.11,'triangle'));
        break;
      case 'charcoalLow':
        if(tryReal(FILE_MAP.charcoalLow as string,0.8)) return;
        this.tone(t,0.14,300,0.1,'sine',240); this.tone(t+0.2,0.14,300,0.1,'sine',240);
        break;
      case 'uiTap':
        if(tryReal(FILE_MAP.uiTap as string,0.7)) return;
        this.tone(t,0.06,700,0.06,'sine',900);
        break;
      case 'uiBack':
        if(tryReal(FILE_MAP.uiBack as string,0.7)) return;
        this.tone(t,0.08,480,0.06,'sine',320);
        break;
      case 'uiError':
        if(tryReal(FILE_MAP.uiError as string,0.7)) return;
        this.tone(t,0.14,220,0.09,'square',160);
        break;
      case 'vipArrive':
        if(tryReal(FILE_MAP.vipArrive as string,0.9)) return;
        this.tone(t,0.5,587,0.11,'triangle'); this.tone(t+0.08,0.45,880,0.08,'sine'); this.noiseBurst(t,0.4,0.04,'highpass',4200,0.6);
        break;
    }
  }

  /** Music: loop real file if decoded, else silent (synth music was removed — real files are mandatory for ship) */
  playMusic(track: 'home'|'gameplay'|'result', opts:{loop?:boolean; gain?:number}={}): void {
    if(this.muted || !this.ctx || !this.musicGain) return;
    this.stopMusic();
    const file=MUSIC_FILES[track];
    const buf=this.buffers.get(file);
    if(!buf) return;
    try{
      const src=this.ctx.createBufferSource();
      src.buffer=buf; src.loop=opts.loop ?? (track!=='result');
      const g=this.ctx.createGain(); g.gain.value= opts.gain ?? 0.55;
      src.connect(g); g.connect(this.musicGain);
      src.start(this.now);
      this.currentMusic={src,gain:g};
      // ducking is handled by caller via setMusicVolume
    }catch{}
  }
  stopMusic(): void {
    if(!this.currentMusic) return;
    try{ this.currentMusic.src.stop(this.now+0.12); }catch{}
    this.currentMusic=null;
  }
  duckMusic(db: number): void {
    if(!this.musicGain || !this.ctx) return;
    const lin=Math.pow(10, db/20);
    this.musicGain.gain.setTargetAtTime(0.6*lin, this.now, 0.18);
  }

  startSizzleBed(): { setIntensity(v: number): void; stop(): void } {
    const noop={setIntensity:()=>{}, stop:()=>{}};
    if(this.muted || !this.ctx || !this.master) return noop;
    // Prefer real loop
    const realBuf=this.buffers.get('sfx_grill_sizzle_loop.wav');
    const crackleBuf=this.buffers.get('sfx_charcoal_crackle_loop.wav');
    if(realBuf){
      const ctx=this.ctx;
      const t=this.now;
      const src=ctx.createBufferSource(); src.buffer=realBuf; src.loop=true; src.playbackRate.value=0.97;
      const lp=ctx.createBiquadFilter(); lp.type='lowpass'; lp.frequency.value=1200;
      const g=ctx.createGain(); g.gain.setValueAtTime(0.0001,t); g.gain.exponentialRampToValueAtTime(0.20,t+0.6);
      src.connect(lp); lp.connect(g); g.connect(this.sfxGain!);
      src.start(t);
      let crackInt: any=null;
      if(crackleBuf){
        const cSrc=ctx.createBufferSource(); cSrc.buffer=crackleBuf; cSrc.loop=true;
        const cGain=ctx.createGain(); cGain.gain.value=0.18;
        cSrc.connect(cGain); cGain.connect(this.sfxGain!);
        cSrc.start(t+0.1);
        crackInt={cSrc, cGain};
      } else {
        // synthetic crackle supplement
        crackInt= globalThis.setInterval(()=>{
          if(!this.ctx||!this.sfxGain||this.muted) return;
          if(Math.random()<0.45) this.noiseBurst(this.now,0.045,0.035,'bandpass',1800+Math.random()*2600,8);
        },240) as any;
      }
      return {
        setIntensity:(v:number)=>{
          const k=Math.max(0,Math.min(1,v));
          const nowT=this.ctx?this.ctx.currentTime:0;
          g.gain.setTargetAtTime(0.08 + k*0.22, nowT, 0.25);
          lp.frequency.setTargetAtTime(600 + k*2200, nowT, 0.3);
          if(crackInt && crackInt.cGain) crackInt.cGain.gain.setTargetAtTime(0.08 + k*0.14, nowT, 0.3);
        },
        stop:()=>{
          if(typeof crackInt==='number' || crackInt?.toString().includes?.('Timeout')) globalThis.clearInterval(crackInt);
          else if(crackInt?.cSrc) try{crackInt.cSrc.stop(this.now+0.3);}catch{}
          try{ g.gain.setTargetAtTime(0.0001,this.now,0.12); src.stop(this.now+0.4);}catch{}
        }
      };
    }
    // Fallback synth bed (original)
    const ctx=this.ctx;
    const t=this.now;
    const src=ctx.createBufferSource(); src.buffer=this.noise!; src.loop=true; src.playbackRate.value=0.85;
    const lp=ctx.createBiquadFilter(); lp.type='lowpass'; lp.frequency.value=900;
    const hp=ctx.createBiquadFilter(); hp.type='highpass'; hp.frequency.value=260;
    const g=ctx.createGain(); g.gain.setValueAtTime(0.0001,t); g.gain.exponentialRampToValueAtTime(0.02,t+0.6);
    src.connect(hp); hp.connect(lp); lp.connect(g); g.connect(this.sfxGain!);
    src.start(t);
    const crackle= globalThis.setInterval(()=>{
      if(!this.ctx||!this.sfxGain||this.muted) return;
      if(Math.random()<0.55) this.noiseBurst(this.now,0.045,0.035,'bandpass',1800+Math.random()*2600,8);
    },220);
    return {
      setIntensity:(v:number)=>{
        const k=Math.max(0,Math.min(1,v));
        const nowT=this.ctx?this.ctx.currentTime:0;
        g.gain.setTargetAtTime(0.006 + k*0.05, nowT, 0.25);
        lp.frequency.setTargetAtTime(500 + k*2200, nowT, 0.3);
      },
      stop:()=>{
        globalThis.clearInterval(crackle);
        try{ g.gain.setTargetAtTime(0.0001,this.now,0.1); src.stop(this.now+0.4);}catch{}
      }
    };
  }
}

export const audio = new PrototypeAudio();
