#!/usr/bin/env node
/**
 * build-runtime — turns the APPROVED masters in Assets/Art into what the prototype loads
 * (docs/22-ARTE_2D_PLANO.md §7.1):
 *
 *   node tools/art/build-runtime.mjs [--include-pending] [--out <dir>]
 *
 *   prototype/assets/art/<name>.webp   each sprite, downscaled to what the game draws
 *   prototype/assets/art/index.json    lookup tables the game uses: foods by ingredient,
 *                                      portraits by customer type, grills by churrasqueira and
 *                                      evolution, backgrounds by restaurant, icons by data id
 *
 * Only rows with status=approved in ASSET_REGISTRY.csv ship (docs/04 §11). `--include-pending`
 * is for looking at a batch in the running prototype before it is approved; never commit a
 * build made with it (the index records the flag, and the review lists it).
 */
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { readFile, writeFile, mkdir, readdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..', '..');
const args = process.argv.slice(2);
const includePending = args.includes('--include-pending');
// --dry-run builds nothing: it reads the registry, computes what would ship and prints the gaps,
// without deleting or rewriting prototype/assets/art. `build-runtime` erases the output folder
// before it re-encodes, so running it by curiosity — to see whether a warning fires — replaces the
// shipped atlas with whatever is `approved` right now. That is how a pending review silently
// downgrades the game the player is looking at.
const DRY_RUN = args.includes('--dry-run');
const outAt = args.indexOf('--out');
const OUT = outAt >= 0 ? join(ROOT, args[outAt + 1]) : join(ROOT, 'prototype', 'assets', 'art');

/** Longest side (px) per category — ~3× the size the 420×780 layout draws them at. */
const MAX_SIDE = { food: 240, character: 200, grill: 1100, prop: 1200, background: 1376, fx: 1100, ui: 128 };
const QUALITY = { background: 84, fx: 84 };

function parseCsv(text) {
  const rows = [];
  for (const line of text.split('\n').filter((l) => l.trim())) {
    const cells = []; let cur = '', q = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (q) { if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; } else if (ch === '"') q = false; else cur += ch; }
      else if (ch === '"') q = true; else if (ch === ',') { cells.push(cur); cur = ''; } else cur += ch;
    }
    cells.push(cur);
    rows.push(cells);
  }
  const [head, ...body] = rows;
  return body.map((r) => Object.fromEntries(head.map((k, i) => [k, r[i] ?? ''])));
}

const manifest = JSON.parse(await readFile(join(ROOT, 'Assets', 'Art', 'sprites.manifest.json'), 'utf8'));
const registry = parseCsv(await readFile(join(ROOT, 'Assets', 'Art', 'ASSET_REGISTRY.csv'), 'utf8'));
const status = Object.fromEntries(registry.map((r) => [r.name, r.status]));
const ships = (name) => status[name] === 'approved' || (includePending && status[name] === 'pending');

if (!DRY_RUN) {
  await mkdir(OUT, { recursive: true });
  for (const f of await readdir(OUT)) if (f.endsWith('.webp') || f === 'index.json') await rm(join(OUT, f));
}

const index = {
  _comment: 'Generated by tools/art/build-runtime.mjs from Assets/Art (approved sprites only unless includePending). Do not edit.',
  includePending,
  sprites: {}, foods: {}, customers: {}, grills: {}, backgrounds: {}, props: {}, fx: {}, icons: {},
};
let bytes = 0;
for (const [name, e] of Object.entries(manifest.sprites).sort(([a], [b]) => a.localeCompare(b))) {
  if (!ships(name)) continue;
  const img = await loadImage(await readFile(join(ROOT, e.file)));
  const s = Math.min(1, (MAX_SIDE[e.category] ?? 512) / Math.max(img.width, img.height));
  const w = Math.max(1, Math.round(img.width * s)), h = Math.max(1, Math.round(img.height * s));
  const c = createCanvas(w, h);
  const ctx = c.getContext('2d');
  ctx.imageSmoothingQuality = 'high';
  ctx.drawImage(img, 0, 0, w, h);
  const buf = c.toBuffer('image/webp', QUALITY[e.category] ?? 88);
  if (!DRY_RUN) await writeFile(join(OUT, `${name}.webp`), buf);
  bytes += buf.length;
  const entry = { file: `${name}.webp`, w, h };
  if (e.hole) {
    const k = w / img.width;
    entry.hole = {
      bbox: e.hole.bbox.map((v) => +(v * k).toFixed(1)),
      quad: e.hole.quad.map(([x, y]) => [+(x * k).toFixed(1), +(y * k).toFixed(1)]),
      tiltDeg: e.hole.tiltDeg,
    };
  }
  index.sprites[name] = entry;

  // lookup tables, from the naming scheme of docs/04 §11
  let m;
  if ((m = name.match(/^spr_char_customer_(.+?)(?:_([ab]))?$/))) (index.customers[m[1]] ??= []).push(name);
  else if ((m = name.match(/^spr_grill_(.+)_evo(\d+)$/))) (index.grills[m[1]] ??= {})[m[2]] = name;
  else if ((m = name.match(/^bg_restaurant_(.+)$/))) index.backgrounds[m[1]] = name;
  else if ((m = name.match(/^spr_prop_(.+)$/))) index.props[m[1]] = name;
  else if ((m = name.match(/^t_fx_(.+)$/))) index.fx[m[1]] = name;
  else if (name.startsWith('ic_')) index.icons[name] = name;
}
// foods: an ingredient ships only when every frame it needs ships — half the states painted and
// half drawn procedurally reads as a bug, so the whole ingredient falls back instead. The cost is
// that refusing ONE frame holds approved frames out of the game, so say it out loud (docs/22 §7.1).
const skipped = [];
for (const [subject, f] of Object.entries(manifest.foods)) {
  const frames = [...Object.values(f.states), f.served].filter(Boolean);
  const missing = frames.filter((n) => !index.sprites[n]);
  if (!missing.length) index.foods[subject] = { kind: f.kind ?? 'grill', states: f.states, served: f.served };
  else if (frames.length - missing.length) skipped.push(`${subject} (${frames.length - missing.length}/${frames.length} approved, falta ${missing.join(', ')})`);
}
if (skipped.length) console.log(`[runtime] ⚠ incomplete food set${skipped.length > 1 ? 's' : ''}, procedural in game: ${skipped.join('; ')}`);
// Grills fall back per evolution — cheaper than a half-shipped ingredient, but it still shows: the
// shop paints one level and procedurally draws the next, and the procedural bed is the size of the
// *old* standard (docs/22 §6.8), so the upgrade looks like a downgrade. Name the levels that lose
// their painted opening, because `set-status … pending` on an already-shipped grill does exactly this.
const grillGaps = [];
for (const ch of JSON.parse(await readFile(join(ROOT, 'shared', 'data', 'churrasqueiras.json'), 'utf8')).churrasqueiras) {
  const missing = ch.evolutions
    .map((e) => `spr_grill_${ch.id}_evo${e.level}`)
    .filter((n) => manifest.sprites[n] && !index.sprites[n]);
  if (missing.length) grillGaps.push(`${ch.id}: ${missing.map((n) => n.replace(/^spr_grill_.+?_evo/, 'evo')).join(', ')}`);
}
if (grillGaps.length) console.log(`[runtime] ⚠ sem arte aprovada (leito procedural, boca fora do padrão): ${grillGaps.join(' · ')}`);
if (!DRY_RUN) await writeFile(join(OUT, 'index.json'), JSON.stringify(index, null, 1) + '\n');
const count = Object.keys(index.sprites).length;
console.log(`[runtime] ${DRY_RUN ? 'dry run: ' : ''}${count} sprites (${(bytes / 1e6).toFixed(2)} MB webp) ${DRY_RUN ? 'sairiam para' : '→'} ${OUT.replace(ROOT + '/', '')}${includePending ? '  ⚠ includes PENDING art — do not commit' : ''}`);
console.log(`[runtime] foods ${Object.keys(index.foods).length} · customers ${Object.keys(index.customers).length} · grills ${Object.entries(index.grills).map(([k, v]) => `${k}(${Object.keys(v).join(',')})`).join(' ')} · backgrounds ${Object.keys(index.backgrounds).join(',') || '-'} · icons ${Object.keys(index.icons).length}`);
